export enum GamePhase {
  MAIN_MENU = 'MAIN_MENU',
  PROPERTY_SELECT = 'PROPERTY_SELECT',
  BUILD = 'BUILD',
  SHOW_SELECT = 'SHOW_SELECT',
  AUDITION = 'AUDITION',
  CREW_HIRE = 'CREW_HIRE',
  REHEARSAL = 'REHEARSAL',
  MARKETING = 'MARKETING',
  RUN = 'RUN',
  SUMMARY = 'SUMMARY',
}

export enum RoomType {
  LOBBY = 'LOBBY',
  BOX_OFFICE = 'BOX_OFFICE',
  SEATING = 'SEATING',
  STAGE = 'STAGE',
  BACKSTAGE = 'BACKSTAGE',
  DRESSING_ROOM = 'DRESSING_ROOM',
  ORCHESTRA_PIT = 'ORCHESTRA_PIT',
  REHEARSAL_HALL = 'REHEARSAL_HALL',
  VIP_LOUNGE = 'VIP_LOUNGE',
  CONCESSION = 'CONCESSION',
  STORAGE = 'STORAGE',
  OFFICE = 'OFFICE',
  TECH_BOOTH = 'TECH_BOOTH',
  GREEN_ROOM = 'GREEN_ROOM',
  RESTROOMS = 'RESTROOMS',
}

export enum ShowGenre {
  MUSICAL = 'MUSICAL',
  PLAY = 'PLAY',
  REVIVAL = 'REVIVAL',
  EXPERIMENTAL = 'EXPERIMENTAL',
}

export enum ShowArchetype {
  CROWD_PLEASER = 'CROWD_PLEASER',
  CRITICS_DARLING = 'CRITICS_DARLING',
  BIG_SPECTACLE = 'BIG_SPECTACLE',
  INTIMATE_CHAMBER = 'INTIMATE_CHAMBER',
  DARK_HORSE = 'DARK_HORSE',
  SAFE_BET = 'SAFE_BET',
}

export enum PropertyCondition {
  POOR = 'POOR',
  FAIR = 'FAIR',
  GOOD = 'GOOD',
  EXCELLENT = 'EXCELLENT',
  PRISTINE = 'PRISTINE',
}

export enum CrewRole {
  DIRECTOR = 'DIRECTOR',
  STAGE_MANAGER = 'STAGE_MANAGER',
  LIGHTING_DESIGNER = 'LIGHTING_DESIGNER',
  SOUND_DESIGNER = 'SOUND_DESIGNER',
  COSTUME_DESIGNER = 'COSTUME_DESIGNER',
  SET_DESIGNER = 'SET_DESIGNER',
  CHOREOGRAPHER = 'CHOREOGRAPHER',
  MUSIC_DIRECTOR = 'MUSIC_DIRECTOR',
  PUBLICIST = 'PUBLICIST',
  HOUSE_MANAGER = 'HOUSE_MANAGER',
}

export enum GameSpeed {
  PAUSED = 0,
  NORMAL = 1,
  FAST = 2,
  ULTRA = 4,
}
